WebApplication1/Controllers/ActividadesController.cs
using Dominio;
using Dominio.Models;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ActividadesController : Controller
    {
        Sistema s = Sistema.GetInstancia();
        public IActionResult ListarActividades()
        {
            ViewBag.Actividades = Sistema.GetInstancia().GetActividadesPorfecha(DateTime.Today);
            return View();
        }

        public IActionResult ListarActividadesSegunFecha(DateTime fechaDada)
        {

            try
            {
                if (fechaDada == DateTime.MinValue)
                {
                    throw new Exception("Debe seleccionar una fecha");
                }

                ViewBag.Actividades = Sistema.GetInstancia().GetActividadesPorfecha(fechaDada);

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;

            }

            return View("ListarActividades");
        }

    }
}

WebApplication1/Controllers/AgendaController.cs
using Dominio;
using Dominio.Models;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class AgendaController : Controller
    {
        Sistema s = Sistema.GetInstancia();

        public IActionResult Agendar(int id)
        {
            //conrolar que exista una personaz logueada y que ademas sea huesped. Si es huesped, sigo de largo
            if (HttpContext.Session.GetString("LogueadoTipo") != null && HttpContext.Session.GetString("LogueadoTipo") == "Huesped")
            {
                try
                {
                    Huesped h = s.GetHuesped(HttpContext.Session.GetInt32("LogueadoId"));
                    Actividad a = s.GetActividad(id);
                    Reserva r = new Reserva(a, h, "PENDIENTE_PAGO", DateTime.Today);
                    s.AltaReservaNuevaAgenda(r);
                    ViewBag.Reserva = r;
                    return View("ResultadoReserva");

                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                    return View("ResultadoReserva");
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }


        public IActionResult ListarAgendas()
        {
            if (HttpContext.Session.GetInt32("LogueadoId") != null)
            {
                if (HttpContext.Session.GetString("LogueadoTipo") == "Operador")
                {
                    List<Reserva> agendas = s.GetReservasConSort();
                    return View(agendas);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ListarAgendasPorHuesped()
        {
            if (HttpContext.Session.GetInt32("LogueadoId") != null)
            {
                if (HttpContext.Session.GetString("LogueadoTipo") == "Operador")
                {
                    return View();
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]

        public IActionResult ListarAgendasPorHuesped(string tipoDoc, string numDoc)
        {
            //El tipo de documento no se puede validar que esté vacío porque siempre va a devolver algo (es un select)
            //Se valida que el numero de documento no este vacio:
            if (string.IsNullOrEmpty(numDoc))
            {
                ViewBag.msg = "El número de documento no puede estar vacío.";
                return View();
            }
            Huesped h = s.GetHuespedDocumento(tipoDoc, numDoc);
            if (h != null)
            {
                List<Reserva> agendasHuesped = s.GetReservasPorHuesped(h);
                if (agendasHuesped.Count == 0)
                {
                    ViewBag.msgSinAgendaHuesped = $"El huésped {h.Nombre} {h.Apellido} no tiene agendas.";
                    return View();
                }
                return View(agendasHuesped);
            }
            ViewBag.msg = "Datos Erróneos";
            return View();

        }

        //Listado de Agendas por fecha. Por defecto muestra las agendas del dia actual.
        public IActionResult ListarAgendasPorFecha()
        {
            if (HttpContext.Session.GetInt32("LogueadoId") != null)
            {
                if (HttpContext.Session.GetString("LogueadoTipo") == "Operador")
                {
                    List<Reserva> agendas = s.GetReservasDeHoy();
                    if (agendas.Count == 0)
                    {
                        ViewBag.msg = "No hay agendas en el día de hoy.";
                        return View(agendas);
                    }
                    return View(agendas);
                }
            }
            return RedirectToAction("Index", "Home");
        }



        [HttpPost]
        public IActionResult ListarAgendasPorFecha(DateTime fecha)
        {
            if (fecha != DateTime.MinValue)
            {
                List<Reserva> agendasPorFecha = s.GetReservasPorFecha(fecha);
                if (agendasPorFecha.Count == 0)
                {
                    ViewBag.msgNoAgendaFechaBuscada = "No hay agendas en la fecha buscada.";
                    return View(agendasPorFecha);
                }
            }
            ViewBag.msgFaltaIngresarFecha = "Debe ingresar una fecha.";

            //Si no se selecciono una fecha se vuelve a mostrar la vista principal con las agenda del dia actual.
            List<Reserva> agendas = s.GetReservasDeHoy();
            if (agendas.Count == 0)
            {
                ViewBag.msg = "No hay agendas en el día de hoy.";
                return View(agendas);
            }
            return View(agendas);
        }


        public IActionResult Edit(int id)
        {
            if (HttpContext.Session.GetInt32("LogueadoId") != null)
            {
                if (HttpContext.Session.GetString("LogueadoTipo") == "Operador")
                {
                    Reserva r = s.GetReserva(id);
                    s.ConfirmarAgenda(id);
                    TempData["msgAgendaConfirmada"] = "Agenda Confirmada con éxito";
                    return RedirectToAction("ListarAgendas");
                }
            }
            return RedirectToAction("Index", "Home");

        }

        public IActionResult AgendasDelHuesped()
        {
            if (HttpContext.Session.GetInt32("LogueadoId") != null)
            {
                if (HttpContext.Session.GetString("LogueadoTipo") == "Huesped")
                {
                    Huesped h = s.GetHuesped(HttpContext.Session.GetInt32("LogueadoId"));
                    List<Reserva> agendasHuesped = s.GetReservasDelHuespedFechaPosteriorAHoy(h);
                    if (agendasHuesped.Count == 0)
                    {
                        ViewBag.Msg = "Usted no tiene agendas.";
                    }
                    return View(agendasHuesped);
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Obligatorio2 </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nombre del Hostal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        @*//Si el usuario esta logueado se muestra el link logout, si no, se muestra el link login y Alta Huesped, mas los links que corresponta segun el tipo de usuario*@

                        @if (Context.Session.GetInt32("LogueadoId") != null)
                        {
                            @if (Context.Session.GetString("LogueadoTipo") == "Huesped") 
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="ListarActividades">Ver Actividades</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="AgendasDelHuesped">Ver mis Agendas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="DetallesHuesped">Ver mi perfil</a>
                                </li>
                            }
                            else if (Context.Session.GetString("LogueadoTipo") == "Operador")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="ListarActividades">Ver Actividades</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Agenda" asp-action="ListarAgendas">Listar Agendas</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor" asp-action="ListarProveedores">Listar Proveedores</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Details">Ver mi perfil</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Create">Alta Huésped</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actividades" asp-action="ListarActividades">Ver Actividades</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ORT P2 M2C - Obligatorio 2 - Díaz - Domínguez
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>